"""add: tracks

Revision ID: bfda0abe3a31
Revises: fdee927134bd
Create Date: 2026-06-21 20:03:03.282179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfda0abe3a31'
down_revision: Union[str, Sequence[str], None] = 'fdee927134bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.Enum('YANDEX', 'SPOTIFY', name='tracksource'), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('yt_url', sa.String(length=512), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tracks_source_source_id', 'tracks', ['source', 'source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracks_source_source_id', table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
